Add common problems page
subspace/subspace-docs pull request #197
Opened 2023-08-09 02:29 UTC by EmilFattakhov

This PR adds a new page for the node docs with an overview of common problems and identifies which of the errors can be ignored, and which ones require attention. 

All information is taken from our Discord and Forum, provided solutions and responses are mostly Justin's and Nazar's comments. 

Please have a look and let me know if you see any errors worth adding to the list, of any incorrect solutions/responses. 

Thanks!

2023-08-09 10:00 UTC, jim-counter requested changes
We should not type the code blocks as it leads to keywords being highlighted that could cause confusion. I have only raised issues in the first copy of the page but they will need repeating for the extra version.

Otherwise, great initiative to help support our community!

2023-08-09 20:07 UTC, EmilFattakhov commented on docs/protocol/common_problems.md
> +- Verify your balance using the [proper explorer](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc-0.gemini-3e.subspace.network%2Fws#/explorer)
Proper Polkadot explorer xD

2023-08-09 20:14 UTC, EmilFattakhov commented on docs/protocol/common_problems.md
> +As the database gets fuller and blocks get bigger (as farmers started to produce votes), it is expected that the sync speed will settle on a smaller number. We have done some performance improvements
That sounds better, thanks!

2023-08-09 20:19 UTC, EmilFattakhov commented on docs/protocol/common_problems.md
> +The system is detecting a pre-existing installation. If this is the case, you might consider wiping the current setup and re-initializing the CLI to ensure a clean installation.
Good idea, added

2023-08-09 21:04 UTC, jim-counter approved these changes
LGTM. Thanks for the revisions @EmilFattakhov 👍

2023-08-10 20:36 UTC, ImmaZoni approved these changes
Looks great to me, thanks Emil! 🙏

2023-08-10 20:38 UTC, merged