Update security.md
subspace/subspace-docs pull request #293
Opened 2023-10-29 16:03 UTC by mathematicw

The part on general security tips has been significantly improved. Added a guide to basic server security.

2023-10-30 03:33 UTC, mathematicw commented
I think pages with huge bright red or yellow banners with exclamation points are not serious style. Warnings at such a strong level about what every cryptan should already know - makes our site less mature. At the same time - it is a fact - that everything written on this page is equally important! Otherwise why write it there? From this I propose to conclude - that bright red highlights should be used only where there is a) temporary necessity b) it is really much more important than everything else that is written on the page.

2023-10-30 18:13 UTC, EmilFattakhov requested changes
Thank you for your contribution @mathematicw, I think you've got some great ideas here!
Requesting mostly wording improvements and typos, there's probably plenty I've missed, so I recommend you check the code through ChatGPT or any other tool for any grammar tweaks.

2023-10-30 18:13 UTC, EmilFattakhov commented on docs/protocol/security.md
> +*let's assume you just got a new server*
I'd suggest to add a note about why it's needed, instead of this message and `etc ... check every SSD`

2023-10-30 18:13 UTC, EmilFattakhov commented on docs/protocol/security.md
> +First make sure you have not UFW enabled. Or add the rule with the desired port to it.
```suggestion
First, make sure you don't have UFW enabled. If you do, add a rule for the desired port."
```

2023-10-30 18:13 UTC, EmilFattakhov commented on docs/protocol/security.md
> + *Remember: add this port to UFW*
We can use `:::note` to communicate this better

2023-10-30 18:13 UTC, EmilFattakhov commented on docs/protocol/security.md
> +manually transfer the public key file and add it to the authorized_keys file on the remote server.
```suggestion
Manually transfer the public key file and add it to the authorized_keys file on the remote server. 
```

2023-10-30 18:13 UTC, EmilFattakhov commented on docs/protocol/security.md
> +To get in touch of Release Notes simply use search https://ubuntu.com/search?q=Ubuntu+22.04+Changelogs
Let's make this a hyperlink

2023-10-31 04:31 UTC, mathematicw commented on docs/protocol/security.md
> + Be sure to make the password long enough, combining both registers letters, numbers and special characters. An 11-character password increases the bruteforce attack time to normally impossible limit
Thank you :)

2023-10-31 04:42 UTC, mathematicw commented on docs/protocol/security.md
> +# 1. Wallet security
Hmm. Yes, really without paragraph numbers, the whole document is easier to read! Thank you

2023-10-31 07:10 UTC, mathematicw commented on docs/protocol/security.md
> +manually transfer the public key file and add it to the authorized_keys file on the remote server.
Got it

2023-11-01 17:01 UTC, closed without merging