Update state pruning command
subspace/subspace-docs pull request #295
Opened 2023-10-30 17:30 UTC by EmilFattakhov

Small documentation update to reflect https://github.com/subspace/subspace/pull/2177

2023-10-30 23:07 UTC, jim-counter requested changes

2023-10-30 23:07 UTC, jim-counter commented on docs/protocol/substrate-cli.mdx
> +    --state-pruning archive-canonical-canonical `
```suggestion
    --state-pruning archive-canonical `
```

2023-10-30 23:07 UTC, jim-counter commented on docs/protocol/substrate-cli.mdx
> +    --state-pruning archive-canonical-canonical \
```suggestion
    --state-pruning archive-canonical \
```

2023-10-31 06:35 UTC, EmilFattakhov commented on docs/protocol/substrate-cli.mdx
> +    --state-pruning archive-canonical-canonical `
Oops, how did that happen!

2023-10-31 11:22 UTC, jim-counter approved these changes
Thanks Emil.

2023-10-31 11:22 UTC, merged