Partition mount
subspace/subspace-docs pull request #308
Opened 2023-10-31 23:19 UTC by mathematicw

Another menu item on the left side of the documentation page.
A detailed guide to partitioning, creating file systems (XFS, EXT4, VFAT and BTRFS) and mounting, with links to recognized manuals. There is useful information on computer science. Of course, this tutorial could be updated and improved. But overall, I can see how this kind of material could be useful, because the idea is to get all the information you need to run a great farm in one place. 
In order to do this brilliantly, it might take some time to properly assess what information is unnecessary and what information is actually useful for most future community members.
I suppose it makes sense to add RAID in the near future, and something will probably turn out to be unnecessary :)

2023-11-01 15:17 UTC, EmilFattakhov requested changes
Thank you for your contribution, a lot of useful information here. 
Requesting some improvements mostly with formatting, display and wording. 
Let's also remove all the changes that are already reflected in your other PRs, e.g. we can remove the whole `security.md` file

2023-11-01 15:17 UTC, EmilFattakhov commented on versioned_docs/version-latest/protocol/Partition-mount.md
> +    The main partition table in MBR partitioning scheme starts in the very first sector of the storage device (the 0th sector). This is also known as the Master Boot Record sector. This sector is a 5
Formatting for the section looks incorrect and shows up a one very long string on a web version.

2023-11-01 15:17 UTC, EmilFattakhov commented on versioned_docs/version-latest/protocol/Partition-mount.md
> +#### [parted](https://www.gnu.org/software/parted/)
```suggestion
#### [Parted](https://www.gnu.org/software/parted/)
```

2023-11-01 15:17 UTC, EmilFattakhov commented on versioned_docs/version-latest/protocol/Partition-mount.md
> +##### Works with both GPT and MBR partition tables. It can resize partitions, but it does not resize the file systems within them. To resize file systems, you may need to use utilities like e2fsprogs
Doesn't need to be a header, please remove ####

2023-11-01 15:17 UTC, EmilFattakhov commented on versioned_docs/version-latest/protocol/Partition-mount.md
> +##### This utility is specifically designed for working with ext2 and ext3 file systems.
Doesn't need to be a header

2023-11-01 15:17 UTC, EmilFattakhov commented on versioned_docs/version-latest/protocol/Partition-mount.md
> +sgdisk can be used as automated script for partition tasks on multiple disks or partitions.
```suggestion
Sgdisk can be used as an automated script for partition tasks on multiple disks or partitions.
```

2023-11-01 15:17 UTC, EmilFattakhov commented on versioned_docs/version-latest/protocol/Partition-mount.md
> + -v	checks for a variety of problems, such as incorrect CRCs and mismatched main and backup data. But does not automatically correct most problems; -c	change-name=partnum:name; -t partition_number:he
Let's make `-v` a code snippet for readability

2023-11-01 15:17 UTC, EmilFattakhov commented on versioned_docs/version-latest/protocol/Partition-mount.md
> +#### [calculator](https://www.unitconverters.net/data-storage/block-to-gigabyte.htm) blocks to gigabytes
```suggestion
#### [Calculator](https://www.unitconverters.net/data-storage/block-to-gigabyte.htm) blocks to gigabytes
```

2023-11-01 15:17 UTC, EmilFattakhov commented on versioned_docs/version-latest/protocol/Partition-mount.md
> +###### note: external-journal have same block size as it's main filesystem (normally, it is so by default)
You can use 
```
:::note 
your note
:::
```

2023-11-01 15:17 UTC, EmilFattakhov commented on versioned_docs/version-latest/protocol/Partition-mount.md
> +    nobarrier (For ex. : `mount -o nobarrier /dev/device /mount/point`) For devices with non-volatile, battery-backed write caches and those with write-caching disabled, you can safely disable write
Wrong formatting, this is shown as a code block, while a lot of it is a plaint text. This is the case for the next 3 sections.

2023-11-01 15:17 UTC, EmilFattakhov commented on versioned_docs/version-latest/protocol/Partition-mount.md
> +    Unlike some other file systems that support external journals, such as XFS and ext4, Btrfs does not support external journaling. The journaling in Btrfs is integrated) into its COW mechanism and
Formatting issues with this section as well.

2023-11-01 15:17 UTC, EmilFattakhov commented on versioned_docs/version-latest/protocol/Partition-mount.md
> +ChatGPT
Looks unrelated

2023-11-01 15:17 UTC, EmilFattakhov commented on versioned_docs/version-latest/protocol/Partition-mount.md
> +## mount commands
```suggestion
## Mount commands
```

2023-11-01 15:17 UTC, EmilFattakhov commented on versioned_docs/version-latest/protocol/Partition-mount.md
> +#### This command usually given in a bootscript causes all filesystems mentioned in fstab to be mounted, exept with -noauto flag:
This one and similar below don't need to be a header

2023-11-01 15:17 UTC, EmilFattakhov commented on versioned_docs/version-latest/protocol/Partition-mount.md
> +### chroot
```suggestion
### Chroot
```

2023-11-01 15:17 UTC, EmilFattakhov commented on versioned_docs/version-latest/protocol/Partition-mount.md
> +async
Let's put all code examples below as code snippets

2023-11-01 15:17 UTC, EmilFattakhov commented on versioned_docs/version-latest/protocol/Partition-mount.md
> +    Maximum amount of time ext4 should wait for additional filesystem operations to be batch together with a synchronous write operation. Since a synchronous write operation is going to force a commi
Formatting

2023-11-01 15:17 UTC, EmilFattakhov commented on versioned_docs/version-latest/protocol/pulsar.mdx
> +| CPU      | 4 Core           |
Looks like this section shouldn't be changed

2023-11-01 15:17 UTC, EmilFattakhov commented on versioned_docs/version-latest/protocol/security.md
> +title: General and server security guidelines
These changes are reflected in your other PR, let's keep the improvements separate and remove the changes from this PR, please :)

2023-11-01 16:42 UTC, mathematicw commented on versioned_docs/version-latest/protocol/Partition-mount.md
> +    The main partition table in MBR partitioning scheme starts in the very first sector of the storage device (the 0th sector). This is also known as the Master Boot Record sector. This sector is a 5
This is done to make it easy to read and compact at the same time. I have specially placed this text in a block with the "Toggle word wrap" function. There is a functionality that allows people to read this text comfortably, not as one very long line, but as normal text block.

2023-11-01 16:44 UTC, mathematicw commented on versioned_docs/version-latest/protocol/Partition-mount.md
> +    The main partition table in MBR partitioning scheme starts in the very first sector of the storage device (the 0th sector). This is also known as the Master Boot Record sector. This sector is a 5
But it's probably worth putting the whole text on the page. As it is not so large

2023-11-01 16:52 UTC, mathematicw commented on versioned_docs/version-latest/protocol/Partition-mount.md
> +    The main partition table in MBR partitioning scheme starts in the very first sector of the storage device (the 0th sector). This is also known as the Master Boot Record sector. This sector is a 5
> This section is duplicated below with slightly different information and numbers.

Are you suggesting to combine these two quite similar sections (the first which is about MBR and the second which is about GPT) into one text block and thus reduce duplicates?

2023-11-01 16:55 UTC, mathematicw commented
> Thank you for your contribution, a lot of useful information here. Requesting some improvements mostly with formatting, display and wording. Let's also remove all the changes that are already reflected in your other PRs, e.g. we can remove the whole `security.md` file

I'm sorry, I didn't catch your point. Did we speak about deleting whole security.md file?

2023-11-01 17:34 UTC, mathematicw commented
> Thank you for your contribution, a lot of useful information here. Requesting some improvements mostly with formatting, display and wording. Let's also remove all the changes that are already reflected in your other PRs, e.g. we can remove the whole `security.md` file

Ok

2023-11-06 19:28 UTC, mathematicw commented
Yeah, I can see there's a lot of work to be done here. It's gonna take me a couple days to get it right.

2023-11-07 22:35 UTC, EmilFattakhov commented on versioned_docs/version-latest/protocol/Partition-mount.md
> +    The main partition table in MBR partitioning scheme starts in the very first sector of the storage device (the 0th sector). This is also known as the Master Boot Record sector. This sector is a 5
Yes, I think we can combine the information from both of them to one section.

2023-11-07 22:36 UTC, EmilFattakhov commented
> Yeah, I can see there's a lot of work to be done here. It's gonna take me a couple days to get it right.

2023-12-27 17:13 UTC, mathematicw commented
Do we need this 'partition mounting' article?

2023-12-31 10:10 UTC, closed without merging

2023-12-31 10:24 UTC, mathematicw commented
I deleted this branch. Hope this is correct action. 
And created new PR 383 with only one file : file-systems.md