Verify Discord Role Instructions
subspace/subspace-docs pull request #511
Opened 2024-05-09 19:06 UTC by ryyeung

2024-05-09 19:25 UTC, EmilFattakhov requested changes
That's a good start, thanks Ryan!

A few changes required imho:
1. This should be under the "Additional Guide" section, and not a top level article.
2. For the screenshot highlighting - use some software that draws the ovals for you so you couldn't see the strokes. 
3. Need to make few additional screenshots with what the section to claim the role looks like, what is the authorization process, how do you sign the transaction and what are pop up windows you should expect (e.g. authorize discord pop-up window). 
4. We should also add a section about "What if I don't see my wallet in the dropdown many" - something we've discussed on a daily earlier today. You can mimic that by creating a few subwallets locally.

2024-05-10 08:32 UTC, jim-counter requested changes
Can we move it under "Addiitional Guides" please Ryan?

2024-05-10 08:32 UTC, jim-counter commented on docs/farming-&-staking/farming/verified-farmer-discord-role/_category_.json
> +    "label": "Verfiy Your Farmer",
```suggestion
    "label": "Verify Your Farmer",
```

2024-05-10 08:32 UTC, jim-counter commented on docs/farming-&-staking/farming/verified-farmer-discord-role/_category_.json
> +      "description": "Verfiy Your Farmer Through Discord!"
```suggestion
      "description": "Verify Your Farmer Through Discord!"
```

2024-05-12 04:49 UTC, ryyeung commented
@EmilFattakhov Added the screenshots. The sizes of the images make it difficult to format, lmk if you have any tips for this.

2024-05-13 18:22 UTC, EmilFattakhov requested changes
Thanks Ryan, looks much better, almost there!

2024-05-13 18:22 UTC, EmilFattakhov commented on docs/farming-&-staking/farming/additional-guides/verify-farmer.md
> +**If you have earned a block or vote reward**, you can now link your Discord account to your farmer wallet through the Astral application to obtain this role. Here’s how to do it:
Let’s rename “Astral Application” to just “Astral” and make a link, please

2024-05-13 18:22 UTC, EmilFattakhov commented on docs/farming-&-staking/farming/additional-guides/verify-farmer.md
> +3. Find the new "Connect Discord" section within the panel.
Let’s use the name of the section from the screenshot instead of “Connect Discord”.

2024-05-13 18:22 UTC, EmilFattakhov commented on docs/farming-&-staking/farming/additional-guides/verify-farmer.md
> +3. Find the new "Connect Discord" section within the panel.
It should be “Get your Farmer role on Discord”

2024-05-13 18:22 UTC, EmilFattakhov commented on docs/farming-&-staking/farming/additional-guides/verify-farmer.md
> +5. Select **Join our Discord Server** and **Connect your Discord Account!**.
```suggestion
5. Select **Join our Discord Server** and **Connect your Discord Account**!
```
```suggestion
5. Select **Join our Discord Server** and **Connect your Discord Account!**.
```

2024-05-13 23:10 UTC, merged